version: '3.8'

services:
  fastify:
    build:
      context: .
      dockerfile: docker/local/Dockerfile
    container_name: golballyhubfastify-app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=30 -- npm run dev'
    networks:
      - golballyhub
networks:
  golballyhub:
    # driver: bridge
    external: true
